<?php
/**
 * @file
 *
 * A Module to Integrate CKAN and Drupal.
 *
 *
 */
module_load_include('inc', 'ckan', 'ckan.tags');
module_load_include('inc', 'ckan', 'ckan.users');
module_load_include('inc', 'ckan', 'ckan.groups');
module_load_include('inc', 'ckan', 'ckan.licenses');
module_load_include('inc', 'ckan', 'ckan.packages');
function ckan_menu(){
	$items = array();

		$items['ckan/list'] = array(
    'page callback'   => 'ckan_list',
    'access arguments' => array('access content'),
    'type'            => MENU_CALLBACK,
		'file' => 'ckan.packages.inc',
	);
			$items['ckan/tags'] = array(
    'page callback'   => 'ckan_tags',
    'access arguments' => array('access content'),
    'type'            => MENU_CALLBACK,
			'file' => 'ckan.packages.inc',
	);
	$items['ckan/groups'] = array(
    'page callback'   => 'ckan_groups',
    'access arguments' => array('access content'),
    'type'            => MENU_CALLBACK,
	'file' => 'ckan.groups.inc',
	);
	$items['ckan/users'] = array(
    'page callback'   => 'ckan_users',
    'access arguments' => array('access content'),
    'type'            => MENU_CALLBACK,
	'file' => 'ckan.users.inc',
	);
	$items['ckan/licenses'] = array(
    'page callback'   => 'ckan_licenses',
    'access arguments' => array('access content'),
    'type'            => MENU_CALLBACK,
	'file' => 'ckan.licenses.inc',
	);
	$items['admin/config/system/ckan'] = array(
    'title' => 'Ckan',
    'description' => 'Configure Ckan',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ckan_admin_settings_form'),
    'access arguments' => array('administer Ckan'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ckan.admin.inc',
	);
	$items['recline'] = array(
    'title' => 'Ckan',
    'description' => 'Configure Ckan',
    'page callback' => 'ckan_display_recline',
    'access arguments' => array('administer Ckan'),
    'type' => MENU_NORMAL_ITEM,
    );

	return $items;
}
/**
 * reclien
 *
 *
 */
function ckan_display_recline(){
	
$path = drupal_get_path('module', 'ckan');
drupal_add_js($path . '/js/vendor/underscore/1.1.6/underscore.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/backbone/0.5.1/backbone.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/moment/1.6.2/moment.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/jquery.flot/0.7/jquery.flot.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/mustache/0.5.0-dev/mustache.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/bootstrap/2.0.2/bootstrap.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/leaflet/0.3.1/leaflet.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/slickgrid/2.0.1/jquery-ui-1.8.16.custom.min.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/slickgrid/2.0.1/jquery.event.drag-2.0.min.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/slickgrid/2.0.1/slick.grid.min.js', array('weight' => 1));
drupal_add_js($path . '/js/vendor/timeline/20120520/js/timeline.js', array('weight' => 1));

drupal_add_js($path . '/js/src/costco.js', array('weight' => 1));
drupal_add_js($path . '/js/src/model.js', array('weight' => 1));
drupal_add_js($path . '/js/src/backend/base.js', array('weight' => 1));
drupal_add_js($path . '/js/src/backend/memory.js', array('weight' => 1));
drupal_add_js($path . '/js/src/backend/dataproxy.js', array('weight' => 1));
drupal_add_js($path . '/js/src/backend/elasticsearch.js', array('weight' => 1));
drupal_add_js($path . '/js/src/backend/gdocs.js', array('weight' => 1));
drupal_add_js($path . '/js/src/backend/csv.js', array('weight' => 1));
drupal_add_js($path . '/js/src/view.grid.js', array('weight' => 1));
drupal_add_js($path . '/js/src/view.slickgrid.js', array('weight' => 1));
drupal_add_js($path . '/js/src/view.transform.js', array('weight' => 1));
drupal_add_js($path . '/js/src/view.graph.js', array('weight' => 1));
drupal_add_js($path . '/js/src/view.map.js', array('weight' => 1));
drupal_add_js($path . '/js/src/view.timeline.js', array('weight' => 1));
drupal_add_js($path . '/js/src/widget.pager.js', array('weight' => 1));
drupal_add_js($path . '/js/src/widget.queryeditor.js', array('weight' => 1));
drupal_add_js($path . '/js/src/widget.filtereditor.js', array('weight' => 1));
drupal_add_js($path . '/js/src/widget.fields.js', array('weight' => 1));
drupal_add_js($path . '/js/src/view.multiview.js', array('weight' => 1));
drupal_add_js($path . '/js/app.js', array('weight' => 1));

drupal_add_css($path . '/js/vendor/bootstrap/2.0.2/css/bootstrap.css', array('weight' => 1));
drupal_add_css($path . '/js/vendor/leaflet/0.3.1/leaflet.css', array('weight' => 1));
drupal_add_css($path . '/js/vendor/slickgrid/2.0.1/slick.grid.css', array('weight' => 1));
drupal_add_css($path . '/js/vendor/timeline/20120520/css/timeline.css', array('weight' => 1));
drupal_add_css($path . '/css/grid.css', array('weight' => 1));
drupal_add_css($path . '/css/slickgrid.css', array('weight' => 1));
drupal_add_css($path . '/css/graph.css', array('weight' => 1));
drupal_add_css($path . '/css/map.css', array('weight' => 1));
drupal_add_css($path . '/css/multiview.css', array('weight' => 1));
drupal_add_css($path . '/css/site/site.css', array('weight' => 1));
drupal_add_css($path . '/css/style/demo.css', array('weight' => 1));
drupal_add_css($path . '/js/vendor/bootstrap/2.0.2/css/bootstrap-responsive.css', array('weight' => 1));
return theme("recline");

}

/**
 * theme
 *
 *
 */
function ckan_theme() {
	return array(
	'recline' => array(
	'template' => 'recline',
	),
	);
}

/**
 * Initialize the ckan object
 *
 *
 */

function ckan_ckan(){
	static $ckan=null;
	if (!$ckan){
		require_once(dirname(__FILE__) . '/ckan.php');
		$ckan=new Ckan(variable_get('ckan_url', 'http://www.ckan.net/'),variable_get('ckan_api', ''));
	}
	return $ckan;
}

/**
 * create a node extrafield
 *
 */
function ckan_createnodeextra($name,$value){
	$nd = new stdClass(); // We create a new node object
	$nd->type = "ckan_extrafields"; // Or any other content type you want
	$nd->title = "Extra field  ".$name;
	$node->uid = 1;
	$nd->language = LANGUAGE_NONE;
	//$nd->created =strtotime(str_replace("T"," ",$ckan_data-> metadata_created));
	//$nd->changed=strtotime(str_replace("T"," ",$ckan_data-> metadata_last_modified));
	$nd->field_labelchamp[LANGUAGE_NONE][0]['value'] = $name;
	$nd->field_valuechamp[LANGUAGE_NONE][0]['value'] = $value;
	$ndextra = node_submit($nd); // Prepare node for a submit
	node_save($ndextra);
	$nidextra=$ndextra->nid;
	return $nidextra;
}
/**
 * check if a node extrafield exists already
 *
 */
function ckan_checkextra($name,$value){
	$query = db_select('field_data_field_labelchamp', 'l');
	$query->join('field_data_field_valuechamp', 'v', 'l.entity_id = v.entity_id'); // inner_join file_usage table against file_managed
	$query->fields('l', array('entity_id'))->condition('l.field_labelchamp_value', $name, '=')->condition("v.field_valuechamp_value",$value,'=');
	$result = $query->execute();
	$nidextra=key($result->fetchAllAssoc('entity_id'));
	return $nidextra;
}

/**
 * Th hook_cron
 *
 *
 */
function ckan_cron(){
	echo "Debut tags import<br/>";
	ckan_tags();
	echo "fin tags import<br/>";
	echo "Debut users import<br/>";
	ckan_users();
	echo "fin users import<br/>";
	echo "Debut groupes import<br/>";
  ckan_groups();
	echo "fin groupes import<br/>";
	echo "Debut packages import<br/>";
  ckan_list();
	echo "fin packages import<br/>";
}






